artifacts_rooot: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/shnkreddy98/data/blob/main/Chicken-fecal-images.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion